name: Create task definition

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

      cpu:
        required: true
        type: number

      memory:
        required: true
        type: number

      ecr-registry:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true

      AWS_SECRET_ACCESS_KEY:
        required: true

      DOTENV_CONTENT:
        required: true


jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-registry }}:${{ inputs.image-name }}
          push: true

  create-task-definition:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Matheus-Merlos/infrastructure
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get account_id
        id: get_account
        run: |
          account_id=$(aws sts get-caller-identity --query "Account" --output text)
          echo "::set-output name=id::$account_id"


      - name: Create Task Definition
        run: |
          chmod +x ./scripts/create-task-definition.sh
          source ./scripts/create-task-definition.sh

          echo ${{ secrets.DOTENV_CONTENT }} > secrets.txt

          create_task_definition ${{ inputs.image-name }} \
            ${{ inputs.cpu }} \
            ${{ inputs.memory }} \
            ${{ steps.get_account.outputs.id }}.dkr.ecr.eu-central-1.amazonaws.com/${{ inputs.ecr-registry }}:${{ inputs.image-name }} \
            secrets.txt \
            ${{ secrets.EFS_ID }} \
            ${{ secrets.EXECUTION_ROLE_ARN }} \
            ${{ secrets.TASK_ROLE_ARN }}
