name: Create task definition

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

      cpu:
        required: true
        type: number

      memory:
        required: true
        type: number

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true

      AWS_SECRET_ACCESS_KEY:
        required: true

      DOTENV_CONTENT:
        required: true


jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image-name }}:latest
          push: true
